version: '3.2'
services:
  cache:
    deploy:
      replicas: 1 
    image: "cloudpg/cachingondemand:compose"
    command: ["--nogrid", "--config", "/etc/xrootd/xrd_test.conf" ,"--health_port", "8080"] 
    environment:
      REDIR_HOST: 'cache_redirector'
      REDIR_CMSD_PORT: 1213
      ORIGIN_HOST: 'cache_origin'
      ORIGIN_XRD_PORT: 1194
      LOW_WM: 0.80
      HI_WM: 0.90
      CACHE_LOG_LEVEL: 'info'
      CACHE_PATH: '/data/xrd'
      CACHE_RAM_GB: 12
      STREAMS: '256'
      N_PREFETCH: 0
      BLOCK_SIZE: '512k'
    networks:
      - overlay
    expose:
      - "32294"
      - "31113"
    #volumes:
    #  - /home/dciangot/git/xrd-decision:/usr/local/xrd-decision

  redirector:
    image: "cloudpg/cachingondemand:compose"
    command: ["--nogrid", "--config", "/etc/xrootd/xrd_test_redir.conf" ,"--health_port", "8080"] 
    environment:
      REDIR_HOST: 'cache_redirector'
      REDIR_CMSD_PORT: 1213
      REDIR_XRD_PORT: 1094
    networks:
      - overlay
    expose:
      - "1094"
      - "1213"

  origin:
    image: "cloudpg/cachingondemand:compose"
    command: ["--nogrid", "--config", "/etc/xrootd/xrd_test_origin.conf", "--health_port", "8080"]
    networks:
      - overlay
    expose:
      - "1194"

  client:
    image: "cloudpg/cachingondemand:compose"
    command: ["--nogrid", "--config", "/etc/xrootd/xrd_test_origin.conf", "--health_port", "8080"]
    networks:
      - overlay
    expose:
      - "1194"

networks:
  overlay:
